version: '3.8'

services:
  frontend:
    image: personal-portfolio-frontend:latest
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}
      - VITE_API_URL=${BACKEND_URL}
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: personal-portfolio-backend:latest
    ports:
      - "8001:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${BACKEND_URL}
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=warning
      - DB_CONNECTION=sqlite
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
    volumes:
      - ~/backend/storage:/var/www/html/storage
      - ~/backend/database:/var/www/html/database
    restart: unless-stopped
    command: >
      bash -c "php artisan config:clear
      && php artisan cache:clear
      && php artisan view:clear
      && apache2-foreground" 