version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://your-ec2-domain:8001
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://your-ec2-domain:8001
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=base64:quVbfJkVE4MCMxHktiV7T0+LV8OdxImUQ4MfT7+tvSE=
      - APP_DEBUG=false
      - APP_URL=http://your-ec2-domain:8001
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=warning
      - DB_CONNECTION=sqlite
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
    volumes:
      - ./backend/storage:/var/www/html/storage
    restart: unless-stopped 