name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: http://13.51.170.162:8001
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        run: |
          echo "Building frontend image..."
          docker build -t personal-portfolio-frontend:latest ./frontend
          echo "Saving frontend image to tar..."
          docker save personal-portfolio-frontend:latest > frontend.tar
          echo "Frontend tar size: $(ls -lh frontend.tar)"

      - name: Build backend image
        run: |
          echo "Building backend image..."
          docker build -t personal-portfolio-backend:latest ./backend
          echo "Saving backend image to tar..."
          docker save personal-portfolio-backend:latest > backend.tar
          echo "Backend tar size: $(ls -lh backend.tar)"

      - name: Generate production docker-compose
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
        run: |
          # Create docker-compose.prod.yml from template
          envsubst < docker-compose.prod.example.yml > docker-compose.prod.yml
          echo "Generated docker-compose.prod.yml:"
          cat docker-compose.prod.yml

      - name: Copy files to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: 13.51.170.162
          EC2_USERNAME: ubuntu
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          
          # Verify files exist before copying
          ls -lh frontend.tar backend.tar docker-compose.prod.yml
          
          # Copy Docker images and compose file
          scp -v -i ssh_key -o StrictHostKeyChecking=no \
            frontend.tar \
            backend.tar \
            docker-compose.prod.yml \
            $EC2_USERNAME@$EC2_HOST:~/
          
          # Verify files were copied
          ssh -i ssh_key -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST 'ls -lh frontend.tar backend.tar docker-compose.prod.yml'

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: 13.51.170.162
          EC2_USERNAME: ubuntu
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST '
            # Stop existing containers
            docker compose -f docker-compose.prod.yml down || true
            
            # Load new images
            docker load < frontend.tar
            docker load < backend.tar
            
            # Start containers with new images
            docker compose -f docker-compose.prod.yml up -d
            
            # Cleanup
            rm frontend.tar backend.tar docker-compose.prod.yml
          ' 